# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(help_text='The unique user id from the RBE Network')),
                ('password', models.CharField(help_text='The dummy password for log in', max_length=128)),
                ('code', models.CharField(help_text='The code to retrieve an api token with.', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='The code to retrieve an api token with.', max_length=128)),
                ('token_type', models.CharField(help_text='The code to retrieve an api token with.', max_length=128)),
                ('expires_in', models.DateTimeField(help_text='The code to retrieve an api token with.')),
                ('refresh_token', models.CharField(help_text='The code to retrieve an api token with.', max_length=128)),
                ('id_token', models.CharField(help_text='The code to retrieve an api token with.', max_length=512)),
                ('belongs_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rbe_authorize.Profile')),
            ],
        ),
    ]
